version: '3.4'

networks:
  topcoder-dev:
    driver: bridge 

services:
  app:
    depends_on:
      - "postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres;port=5432;database=blogdb;username=bloguser;password=bloguser"
    networks:
      - topcoder-dev  
  
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "blogdb"
    networks:
      - topcoder-dev
volumes:
  db_volume:
         
    
     