version: '3.4'

networks:
  topcoder-dev:
    driver: bridge 

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "example"
      POSTGRES_DB: "userdb"
    networks:
      - topcoder-dev
  app:
    depends_on:
      - "postgres"
    build: .
    ports:
      - "5000:80"
    environment:
      PostgresDB__DATABASE: userdb
      PostgresDB__Host: postgres
      PostgresDB__PORT: 5432
      PostgresDB__USER: root
      PostgresDB__PASSWORD: example
    networks:
      - topcoder-dev  
volumes:
  db_volume:
         
    
     