version: '3.4'

networks:
  topcoder-dev:
    driver: bridge 

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "bloguser"
      POSTGRES_DB: "blogdb"
    networks:
      - topcoder-dev
  app:
    depends_on:
      - "postgres"
    build: .
    ports:
      - "5000:80"     
    environment:
      POSTGRES_DB: blogdb
      POSTGRES__Host: postgres
      POSTGRES__PORT: 5432
      POSTGRES__USER: bloguser
      POSTGRES__PASSWORD: bloguser
    networks:
      - topcoder-dev  
volumes:
  db_volume:
         
    
     